import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {JSDOM} from 'jsdom';import {publicMetadata} from '../seo.mjs';
const root=new URL('../public/',import.meta.url).pathname;
test('every public page gets one canonical and complete share metadata without changing its body',()=>{
const files=fs.readdirSync(root,{recursive:true}).filter(f=>f.endsWith('.html')&&!['pro.html','login.html','report.html','referral.html','404.html'].includes(f));
for(const f of files){const html=fs.readFileSync(path.join(root,f),'utf8'),route=f==='index.html'?'/':'/'+f.slice(0,-5),out=publicMetadata(html,route),dom=new JSDOM(out),doc=dom.window.document;assert.equal(out.split('<body')[1],html.split('<body')[1],f+' body unchanged');assert.equal(doc.querySelectorAll('link[rel="canonical"]').length,1,f);assert.equal(doc.querySelector('link[rel="canonical"]').href,'https://inboxproof.email'+route);for(const key of ['og:title','og:description','og:url','og:image'])assert.equal(doc.querySelectorAll('meta[property="'+key+'"]').length,1,f+' '+key);assert.equal(doc.querySelector('meta[name="twitter:card"]').content,'summary_large_image');for(const s of doc.querySelectorAll('script[type="application/ld+json"]'))assert.doesNotThrow(()=>JSON.parse(s.textContent),f);dom.window.close();}
});
test('HTML aliases canonicalize to the primary URL and unsafe attribute values are escaped',()=>{
const html='<html><head><title>SPF &amp; DMARC</title><meta name="description" content="A &quot;quote&quot;"><link rel="canonical" href="https://old.invalid/"></head><body>Kept</body></html>';const dom=new JSDOM(publicMetadata(html,'/index.html'));assert.equal(dom.window.document.querySelector('link[rel="canonical"]').href,'https://inboxproof.email/');assert.equal(dom.window.document.querySelector('meta[name="twitter:title"]').content,'SPF & DMARC');assert.equal(dom.window.document.querySelector('meta[name="twitter:description"]').content,'A "quote"');dom.window.close();assert.match(publicMetadata(html,'/spf-checker.html'),/https:\/\/inboxproof.email\/spf-checker"/);
});
